phpserver:
  extends:
    file: base.yml
    service: phpserver
  links:
    - mysql:mysql
  cpuset: "%phpserver_cpuset%"
  cpu_shares: %phpserver_cpu_shares%
  mem_limit: %phpserver_memlimit%
  memswap_limit: %phpserver_memlimit%
mysql:
  extends:
    file: base.yml
    service: mysql
  cpuset: "%mysql_cpuset%"
  cpu_shares: %mysql_cpu_shares%
  mem_limit: %mysql_memlimit%
  memswap_limit: %mysql_memlimit%
phpmyadmin:
  extends:
    file: base.yml
    service: phpmyadmin
  links:
    - mysql:mysql