phpserver:
  extends:
    file: base.yml
    service: phpserver
  links:
    - mongo:mongo
  cpuset: "%phpserver_cpuset%"
  cpu_shares: %phpserver_cpu_shares%
  mem_limit: %phpserver_memlimit%
  memswap_limit: %phpserver_memlimit%
mongo:
  extends:
    file: base.yml
    service: mongo
  cpuset: "%mongo_cpuset%"
  cpu_shares: %mongo_cpu_shares%
  mem_limit: %mongo_memlimit%
  memswap_limit: %mongo_memlimit%