webvps:
  build: ./webvps
  container_name: ${WEBVPS_NAME}.webvps
  volumes:
    - ./volumes/www:/var/www
    - ./volumes/mysql:/var/lib/mysql
  environment:
    HOST_NAME: ${WEBVPS_NAME}
    HOST_DOMAIN_NAME: ${WEBVPS_HOST}
    APACHE_USERNAME_UID: ${WEBVPS_UID_WWW}
phpmyadmin:
  image: soletic/phpmyadmin
  container_name: ${WEBVPS_NAME}.webvps.phpmyadmin
